variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # We want full history so that "git describe" always works correctly.
  GIT_DEPTH: 0
  FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"
  # We always want to run with the Go version installed in a Docker image.
  GOTOOLCHAIN: local

test_go:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash gcc musl-dev
    - (cd /go; go install gotest.tools/gotestsum@v1.10.1)
    - (cd /go; go install github.com/boumenot/gocover-cobertura@v1.2.0)

  script:
    - mkdir -p dist
    - touch dist/dummy
    - make test-ci

  artifacts:
    when: always
    reports:
      junit: tests.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - tests.xml
      - coverage.html
      - coverage.xml
    expire_in: never

  coverage: '/coverage: \d+\.\d+% of statements/'

test_node:
  stage: test

  image: node:20.9-alpine3.18

  before_script:
    - apk --update add git git-lfs
    - git lfs fetch

  script:
    - npm ci --audit=false
    - npm run test-ci

  artifacts:
    when: always
    reports:
      junit: tests.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    exclude:
      - coverage/tmp/
    expire_in: never

  coverage: '/^All files\s+\|\s+\S+\s+\|\s+\S+\s+\|\s+\S+\s+\|\s+\S+\s+\|/'

lint_go:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash gcc musl-dev
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

  script:
    - mkdir -p dist
    - touch dist/dummy
    - make lint-ci

  artifacts:
    when: always
    reports:
      codequality: codeclimate.json
    expire_in: never

lint_node:
  stage: test

  image: node:20.9-alpine3.18

  script:
    - npm ci --audit=false
    - npm run lint

lint_vue:
  stage: test

  image: node:20.9-alpine3.18

  script:
    - npm ci --audit=false
    - npm run lint-vue

lint_style:
  stage: test

  image: node:20.9-alpine3.18

  script:
    - npm ci --audit=false
    - npm run lint-style

fmt_go:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash git gcc musl-dev grep
    - go install mvdan.cc/gofumpt@v0.5.0
    - go install golang.org/x/tools/cmd/goimports@v0.13.0

  script:
    - make fmt-ci

fmt_node:
  stage: test

  image: node:20.9-alpine3.18

  script:
    - npm ci --audit=false
    - npm run fmt
    - git diff --exit-code --color=always

lint_docs:
  stage: test

  image: node:20.9-alpine3.18

  before_script:
    - apk --update add make bash

  script:
    - make lint-docs

audit_go:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash git gcc musl-dev
    - go install github.com/sonatype-nexus-community/nancy@v1.0.42

  script:
    - make audit

audit_node:
  stage: test

  image: node:20.9-alpine3.18

  script:
    - npm audit

commits:
  stage: test

  image: golang:1.21-alpine3.18

  variables:
    GIT_DEPTH: "0"

  before_script:
    - apk --update add git

  script:
    - '! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep "^"'
