linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    disabled-checks:
      - ifElseChain
  godot:
    scope: all
  goimports:
    local-prefixes: gitlab.com/charon/charon
  gosimple:
    checks:
      - all
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 170
  nestif:
    min-complexity: 15
  nolintlint:
    allow-unused: false
    require-specific: true
  stylecheck:
    checks:
      - all
  staticcheck:
    checks:
      - all
  tagalign:
    strict: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
    # - cyclop
    # - depguard
    # - funlen
    # - gci
    # - gocognit
    # - gocyclo
    # - godox
    # - nlreturn
    # - varnamelen
    # - wsl

issues:
  exclude-rules:
    - path: utils_test\.go
      linters:
        - testpackage
    - path: .*_test\.go
      linters:
        - exhaustruct
        - goconst
        - lll
        - wrapcheck
