/**
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by generate-vue-i18n.js script based on src/locales/en.json.
 * To update this file, modify src/locales/en.json and run: npm run generate-vue-i18n.
 */

// This empty export makes TypeScript treat this file as a module.
export {}

declare module "vue-i18n" {
  export interface DefineLocaleMessage {
    common: {
      buttons: {
        next: string
        back: string
        retry: string
        create: string
        update: string
        select: string
        enable: string
        decline: string
        cancel: string
        add: string
        remove: string
        disable: string
        activate: string
        addUser: string
        addAdmin: string
        manage: string
        activity: string
        signOut: string
        signIn: string
        resume: string
        pause: string
        redirect: string
        block: string
        unblock: string
      }
      errors: {
        unexpected: string
        wrongPassword: string
        invalidPassword: string
        shortPassword: string
        invalidCode: string
        noAccount: string
        noEmails: string
        invalidEmailOrUsername: {
          email: string
          username: string
        }
        shortEmailOrUsername: {
          email: string
          username: string
        }
        credentialAlreadyUsed: string
        passkeyBoundToOtherAccount: string
      }
      labels: {
        optional: string
        admin: string
        current: string
        active: string
        disabled: string
        added: string
        creator: string
        blocked: string
        shared: string
        individual: string
      }
      data: {
        dataLoading: string
        loadingDataFailed: string
        confirmUpdateToAllocate: string
        adminsUpdated: string
      }
      fields: {
        description: string
        username: string
        email: string
        givenName: string
        fullName: string
        pictureUrl: string
      }
      entities: {
        admins: string
        users: string
        identity: string
        identities: string
        organization: string
        organizations: string
        applicationTemplate: string
        applicationTemplates: string
        activity: string
        credentials: string
        app: string
      }
      messages: {
        congratulations: string
        sorry: string
      }
      time: {
        seconds: string
        paused: string
      }
      accessibility: {
        picture: string
      }
      providers: {
        usernameTitle: string
        emailTitle: string
        password: string
        passwordTitle: string
        passkey: string
        passkeyTitle: string
        code: string
      }
    }
    partials: {
      AuthAutoRedirect: {
        congratulations: string
        declined: string
        redirectMessage: string
        declineSignInOrSignUp: string
      }
      AuthCode: {
        codeSentEmail: string
        codeSentUsername: string
        codeFromHashEmail: string
        codeFromHashUsername: string
        resendButton: string
        sentCount: string
        confirmCode: string
        waitForCode: string
        securityWarning: string
        dont: string
        troubleEmail: string
        differentMethod: string
      }
      AuthIdentity: {
        newIdentityButton: string
        signinSuccess: string
        signupSuccess: string
        previouslyUsedDisabled: string
        otherAvailableIdentities: string
        noIdentitiesCreateFirst: string
        noOtherIdentitiesCreateOne: string
        selectInstructions: string
        previouslyUsedIdentities: string
        createNewIdentity: string
        identitiesUsedWithOrg: string
        disabledIdentities: string
        blockedIdentities: string
        noIdentityUsed: string
        noIdentityUsedWithApp: string
        allPreviousDisabled: string
      }
      AuthManualRedirect: {
        failed: string
        tryAgain: string
        completed: string
        homepage: string
        return: string
      }
      AuthPasskeySignin: {
        signingIn: string
        signupInfo: string
        passkey: string
      }
      AuthPasskeySignup: {
        instructions: string
        signingUp: string
        failed: string
        retrySigninButton: string
        passkeySignupButton: string
        retrySignupButton: string
        passkey: string
        signupInfo: string
      }
      AuthPassword: {
        emailAddressLabel: string
        usernameLabel: string
        passwordLabel: string
        sendCodeButton: string
        emailAccount: string
        usernameAccount: string
        skipPassword: string
        troublePassword: string
        differentSigninMethod: string
      }
      AuthStart: {
        emailOrUsernameLabel: string
        orUse: string
      }
      AuthThirdPartyProvider: {
        redirectMessage: string
        instructions: string
        additionalInfo: string
      }
      Footer: {
        poweredBy: string
      }
      IdentityOrganization: {
        id: string
        status: string
        apps: string
        noApps: string
        statusAndBlocked: string
      }
      ActivityListItem: {
        signin: string
        signout: string
        identityCreate: string
        identityUpdate: string
        organizationCreate: string
        organizationUpdate: string
        applicationTemplateCreate: string
        applicationTemplateUpdate: string
        identityBlocked: string
        accountBlocked: string
        identityUnblocked: string
        changes: {
          otherData: string
          permissionsAdded: string
          permissionsRemoved: string
          applicationsAdded: string
          applicationsRemoved: string
          applicationsChanged: string
          applicationsActivated: string
          applicationsDisabled: string
          organizationsAdded: string
          organizationsRemoved: string
          organizationsChanged: string
          organizationsActivated: string
          organizationsDisabled: string
          identitiesAdded: string
          identitiesRemoved: string
        }
        entityLinks: string
      }
      CredentialFull: {
        verified: string
        notVerified: string
        thirdPartyProviders: string
        passwordSignUp: string
      }
      CredentialAddPassword: {
        label: string
      }
      CredentialAddPasskey: {
        label: string
        passkeyInstructions: string
        passkeyNotSupported: string
        addPasskeyButton: string
      }
    }
    views: {
      ApplicationTemplateCreate: {
        createApplicationTemplate: string
        applicationTemplateName: string
        chooseApplicationTemplateName: string
      }
      ApplicationTemplateGet: {
        applicationTemplateName: string
        homepageTemplate: string
        spaceSeparatedScopes: string
        variables: string
        name: string
        addVariable: string
        publicClients: string
        oidcRedirectUriTemplates: string
        addRedirectUri: string
        spaceSeparatedAdditionalScopes: string
        accessTokenType: string
        hmac: string
        jwt: string
        accessTokenLifespan: string
        idTokenLifespan: string
        refreshTokenLifespan: string
        addClient: string
        backendClients: string
        tokenEndpointAuthMethod: string
        serviceClients: string
        applicationsUpdated: string
        variablesUpdated: string
        publicClientsUpdated: string
        backendClientsUpdated: string
        serviceClientsUpdated: string
      }
      ApplicationTemplateList: {
        noApplicationTemplatesCreate: string
        noApplicationTemplatesSignIn: string
      }
      AuthFlowGet: {
        instructionsMessage: string
      }
      IdentityCreate: {
        createIdentity: string
      }
      IdentityGet: {
        identityUpdated: string
        usersUpdated: string
        organizationsUpdated: string
        addedOrganizations: string
        availableOrganizations: string
      }
      IdentityList: {
        noIdentitiesCreate: string
        noIdentitiesSignIn: string
      }
      OrganizationCreate: {
        createOrganization: string
        organizationName: string
        chooseOrganizationName: string
      }
      OrganizationGet: {
        organizationName: string
        organizationUpdated: string
        addedApplicationsUpdated: string
        identitiesUpdated: string
        addedApplications: string
        availableApplications: string
        addedIdentities: string
        availableIdentities: string
        backendClients: string
        clientId: string
        clientSecret: string
        configuration: string
        publicClients: string
        serviceClients: string
        status: string
      }
      OrganizationList: {
        noOrganizationsCreate: string
        noOrganizationsSignIn: string
      }
      OrganizationUsers: {
        usersForOrganization: string
        noUsers: string
      }
      OrganizationBlockUser: {
        blockUser: string
        blockConfirmation: string
        blockType: string
        blockOnlyIdentity: string
        blockIdentityAndAccounts: string
        organizationNote: string
        userNote: string
        blockingSuccess: string
      }
      ActivityList: {
        noActivities: string
      }
      OrganizationActivity: {
        organizationActivity: string
        noActivities: string
      }
      CredentialAdd: {
        addCredential: string
        availableOptions: string
        credentialTypes: string
      }
      CredentialList: {
        noCredentialsCreate: string
        noCredentialsSignIn: string
        verify: string
      }
    }
  }
}
